language: r
sudo: false
cache: packages
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    env: DRAT_DEPLOY=true
  - os: osx
    osx_image: xcode9.4
  - os: osx
    osx_image: xcode11
    r_build_args: "--no-build-vignettes"
    r_check_args: "--ignore-vignettes --no-examples"
r_packages:
- covr
- drat
r_github_packages:
- cloudyr/travisci
- cloudyr/aws.ec2metadata
after_success:
- R -q -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test
  $DRAT_DEPLOY == "true" && bash drat.sh
- R -q -e "travisci::restart_last_build('cloudyr/awspack')"
env:
  global:
    secure: QcQ85DSaKNDkP9ZtXEIgIjDPe2uGhshWM/Jy3FbLvTZDzizLJhAGyEuQGgfLSG5ZyGF6XDpYeyiqVwhoogKrFprasQupuS2Uovkp2vWIJy6qMMN3gid0AWqEl1gTZdBB53OzqwU3gBvb7bRZfBRgGT4Cdow5oeyIkstOpkB9Xac=
